#!/bin/bash

stty -F $6 9600

sleep 2

# Workaround for macosx gatekeeper, see https://github.com/arduino/Arduino/issues/3468
chmod +x "`dirname "$0"`/dfu-util-bin"
"`dirname "$0"`/dfu-util-bin" -l -d $2 -a $3 -s $4 -D $5
"`dirname "$0"`/dfu-util-bin" -l -d $2 -a $3 --reset-stm32
